module LgPodPlugin

  class LUtils

    # md5加密
    def self.md5: (String text) -> String

    #判断对象是不是 String
    def self.is_a_string?: (String obj) -> bool

    # 解压文件
    def self.unzip_file: (String zip_file, String dest_dir) -> bool

    # 下载 zip 格式文件
    def self.download_gitlab_zip_file:(Pathname path, String token, String download_url, String filename, bool async) -> [String, String]

    # gitlab 下载压缩文件
    def self.download_github_zip_file: (String path, String download_url, String file_name) -> void

    def self.git_to_uri: (String git) -> URI

    # 通过 git ls-remote获取最新 commit
    def self.refs_from_ls_remote: (String git, String branch) -> String

    # 解析git ls-remote结果
    def self.sha_from_result: (String output, String branch_name) -> [String, String]

    #截取git-url 拿到项目绝对名称 比如 l-base-ios
    def self.get_git_project_name: (String git) -> String

    # 截取 url
    def self.get_gitlab_base_url: (String git) -> String

    # url 编码
    def self.url_encode: (String url) -> String

    # pod主库名称
    def self.pod_real_name: (String name) -> String

  end
end
