module LgPodPlugin
  class LUtils
    # 字符串md5加密
    def self.md5:(String text) -> void

    #判断对象是不是 String
    def self.is_a_string?: (obj) -> bool

    # 解压文件
    def self.unzip_file: (String zip_file, String dest_dir) -> bool

    # 下载 zip 格式文件
    def self.download_gitlab_zip_file: (String download_url, String token, String file_name) -> void

    # gitlab 下载压缩文件
    def self.download_github_zip_file: (String download_url, String file_name) -> void

    # 将一个host 转成ip 地址
    # def self.git_server_ip_address: (String git) -> [String, bool]

    #截取git-url 拿到项目名称
    def self.get_git_project_name: (String git) -> String

    # 是否能够使用 gitlab 下载 zip 文件
    def self.is_use_gitlab_archive_file: (String git) -> bool
    # 截取 url
    def self.get_gitlab_base_url: (String git) -> String

    # 根据参数生成下载 url
    def self.get_gitlab_download_url: (String base_url, String branch, String tag, String commit, String project_name) -> String

    def self.git_to_uri:(String git) -> URI
    def self.url_encode: (String url) -> String

  end
end
