module LgPodPlugin

  class LGitUtil

    def git_clone_by_branch: (String path, String temp_name) -> Pathname

    def git_clone_by_tag: (String path, String temp_name) -> Pathname

    # git clone commit
    def git_clone_by_commit: (String path, String temp_name) -> Pathname

    # clone 代码仓库
    def git_clone_repository: (String path) -> Pathname

    # git 预下载
    def pre_download_git_repository: -> void

    # 获取最新的一条 commit 信息
    def self.git_ls_remote_refs: (String git, String branch, String tag, String commit) -> [String, String]

  end
end
