
module LgPodPlugin
  class ProjectModel
  end

  class GitLabAPI

    public

    # 获取 GitLab access_token
    def self.request_gitlab_access_token: (String host, String username, String password) -> void

    #获取用户所有项目
    def self.get_user_projects: (String access_token, String host, String  page) -> void

    # 刷新gitlab_token
    def self.refresh_gitlab_access_token: (String host, String refresh_token) -> void

    # 通过名称搜索项目信息
    def self.request_project_info: (String host, String project_name, String access_token) -> ProjectModel

  end

end