module LgPodPlugin

  class LDownloader

    # 预下载处理
    def pre_download_pod: -> Hash[String, Object]?
    def pre_download_git_repository: (Hash[String, Object] checkout_options) -> Hash[String, Object]?
    def select_git_repository_download_strategy: (Pathname path, Hash[String, Object] checkout_options) -> Hash[String, Object]?
  end

end
