module LgPodPlugin

  class LRequest
    # pod name
    attr_reader name: String
    # gitlab 仓库信息
    attr_accessor config: LConfig
    # 网络状态
    attr_accessor net_ping: Ping
    # 是否只有 git 参数
    attr_accessor single_git: bool
    # 是否是 release_pod
    attr_reader released_pod: false
    # 实际下载请求参数
    attr_accessor params: Hash[Symbol, String]
    # lockfile 文件信息
    attr_accessor lockfile: LgPodPlugin::LockfileModel
    # pod原始请求参数
    attr_accessor checkout_options: Hash[Symbol, String]
  end

end
